spring.application.name=MarketDM

spring.jpa.open-in-view=false

# removing the warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=112130

app.security.remember-me.key=${REMEMBER_ME_SECRET:defaultRememberMeSecret}

#(dev)
spring.security.user.name=springslogin
spring.security.user.password=${ADMIN_PASSWORD:springspassword}
spring.security.user.roles=ADMIN

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

# JWT
jwt.secret=${JWT_SECRET:mySuperSecretKeyThatIsVeryLongAndSecure123!}
jwt.expiration-ms=86400000

app.security.allowed-origins[0]=http://localhost:3000
app.security.allowed-origins[1]=https://myapp.com
app.security.token-expiration-days=7
app.security.password-reset-expiration-minutes=30